### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by rahmansahinler1** [rahmansahinler1/ragchat#10]
**Description**
Application's initial home page. Which will show our vision and product's capabilities.

**Workflow**
1- Design the initial part within the figma
2- Integrate this part into the frontend
3- Make neccesary connections with the backend

**Acceptance Criteria**
Integrated home page

**Comment by iygoktas** [comment]
Finished!

![Image](https://github.com/user-attachments/assets/d7ea631b-1d36-4fde-813b-6cdf037ff334)
![Image](https://github.com/user-attachments/assets/f671892c-9bfa-45a6-8848-a0777f81273a)
![Image](https://github.com/user-attachments/assets/eb09bc3d-b357-43ec-91f3-918f96dcb5b1)
![Image](https://github.com/user-attachments/assets/3830f000-c9a2-4084-8380-9c1198b1b81e)

**Comment by rahmansahinler1** [comment]
Neat work from neat frontend developer!
