### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by rahmansahinler1** [rahmansahinler1/ragchat#11]
**Description**
A basic user sign in page

**Workflow**
1- Design the sign in page within figma
2- Program the frontend parts
3- Integratation with backend

**Acceptance Criteria**
Integrated sign in page

**Comment by iygoktas** [comment]
Done!

Sign-up

![Image](https://github.com/user-attachments/assets/018f29fe-e259-44ee-ab86-31f948fed50f)

Log-in

![Image](https://github.com/user-attachments/assets/cc71982a-08fd-4ff3-b547-180bae902708)
