### ISSUE TITLE
Web App Page Design V2

### ISSUE THREAD

**Issue by rahmansahinler1** [rahmansahinler1/ragchat#15]
**Description**
After initial designed there were additional improvement points on the web application page.

1- Resources line
2- Resources placeholder text (both for domain and resource text)
3- Solid looking upper section
4- Make user text and text boxes smaller
5- Same button styles with figma
6- Drag and drop section explanations
7- Profile icon on the top

**Workflow**
1- Implement necessary updates in the html and css part
2- Review the code
3- Implementation to the develop branch

**Acceptance Criteria**
Implemented improvement ideas to the design

**Comment by iygoktas** [comment]
1 - Done
2 - Done
3 - Done
4 - Done
5 - Done
6 - Done
7 - Done
