### ISSUE TITLE
Assigning Texts to Correct Classes

### ISSUE THREAD

**Issue by iygoktas** [rahmansahinler1/ragchat#24]
The texts pulled via JavaScript in **Resource Section** are not assigned to the correct classes. 

Also, due to a problem not caused by CSS, ellipses are automatically added at the end of the articles, if the classes are introduced correctly as they should be, this problem will dissapear.

In the same way, when I write the text generated by AI in the description class, ellipses are not formed in this way, it can write all of them one after the other.

In the original, it looks like this: 

![image](https://github.com/user-attachments/assets/6fa0fa86-8204-4d49-b423-73a05895695c)

According to this code: 

![image](https://github.com/user-attachments/assets/c7a40ee9-a384-46fa-a859-d1cf4c37e278)

But when AI generates the resources automatically, the resource section loading like this: 

![image](https://github.com/user-attachments/assets/4b6bf2b1-71b0-48de-8a4d-49db88075b12)

**Comment by rahmansahinler1** [comment]
Issue was on the Javascript function.
Fixed with the one that is generating resource with correct structure
