### ISSUE TITLE
Initial Web App Page Design

### ISSUE THREAD

**Issue by rahmansahinler1** [rahmansahinler1/ragchat#4]
**Description**
Figma design for initial web application. This design will only include the necessary parts that demo application must have.

**Workflow**
1- Decide just what needed in the demo
2- Discuss the implementations
3- Design the initial application page

**Acceptance Criteria**
Designed web application page

**Comment by iygoktas** [comment]
**https://www.figma.com/design/HcmpyE2aE9ETM9D9mjFrp8/RAGChat-Demo?m=auto&t=ft2nxt0L0hhvEQdi-6**

![Image](https://github.com/user-attachments/assets/2fe2ade7-f165-4cf9-be54-77bf5ed444b0)

**Comment by rahmansahinler1** [comment]
Nice!
